// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA7uY-6iGxj5hO2pESiJZOymf8gQGq0EI',
    appId: '1:1080771589911:web:48f81fe0b384cb1285a952',
    messagingSenderId: '1080771589911',
    projectId: 'clicker-em-flutter',
    authDomain: 'clicker-em-flutter.firebaseapp.com',
    storageBucket: 'clicker-em-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXZZSmgfqEV-E_fF2iLwi8kLSPkcrH8U4',
    appId: '1:1080771589911:android:d34dcd996ab6e0fa85a952',
    messagingSenderId: '1080771589911',
    projectId: 'clicker-em-flutter',
    storageBucket: 'clicker-em-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtN0fmfBn6gUbcOPJghjHsIrH-YN4ft-4',
    appId: '1:1080771589911:ios:80e096a7f921fd1885a952',
    messagingSenderId: '1080771589911',
    projectId: 'clicker-em-flutter',
    storageBucket: 'clicker-em-flutter.firebasestorage.app',
    iosBundleId: 'com.example.clickerEmFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtN0fmfBn6gUbcOPJghjHsIrH-YN4ft-4',
    appId: '1:1080771589911:ios:80e096a7f921fd1885a952',
    messagingSenderId: '1080771589911',
    projectId: 'clicker-em-flutter',
    storageBucket: 'clicker-em-flutter.firebasestorage.app',
    iosBundleId: 'com.example.clickerEmFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA7uY-6iGxj5hO2pESiJZOymf8gQGq0EI',
    appId: '1:1080771589911:web:75194b8209e26a5585a952',
    messagingSenderId: '1080771589911',
    projectId: 'clicker-em-flutter',
    authDomain: 'clicker-em-flutter.firebaseapp.com',
    storageBucket: 'clicker-em-flutter.firebasestorage.app',
  );
}
